# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=20)),
                ('access_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'IP地址',
                'verbose_name': 'IP地址',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='times',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='article',
            name='accessip',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.AccessIp'),
        ),
    ]
