# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170308_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessip',
            name='access_time',
            field=models.DateTimeField(),
        ),
    ]
