# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170308_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='accessip',
        ),
        migrations.AddField(
            model_name='article',
            name='accessip',
            field=models.ManyToManyField(to='blog.AccessIp'),
        ),
    ]
